name: LunarCalendarApp
options:
  deploymentTarget:
    macOS: '14.0'
settings:
  base:
    SWIFT_VERSION: 6.0
    SWIFT_STRICT_CONCURRENCY: complete
targets:
  LunarCalendarApp:
    type: application
    platform: macOS
    deploymentTarget: '14.0'
    sources:
      - path: Sources/LunarCalendarApp
    info:
      path: LunarCalendarApp/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSCalendarsFullAccessUsageDescription: LunarCalendar needs Calendar access to show your events in the agenda.
        NSRemindersFullAccessUsageDescription: LunarCalendar needs Reminders access to show your reminders in the agenda.
    entitlements:
      path: LunarCalendarApp/LunarCalendarApp.entitlements
      properties:
        com.apple.security.network.client: true
        com.apple.security.personal-information.calendars: true
        com.apple.security.personal-information.reminders: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.reinamaccredy.lunarcalendar
        PRODUCT_NAME: LunarCalendar
        MARKETING_VERSION: 1.0.4
        CURRENT_PROJECT_VERSION: 104
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: ''
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
schemes:
  LunarCalendarApp:
    build:
      targets:
        LunarCalendarApp: all
    run:
      config: Debug
    test:
      config: Debug
